### ISSUE TITLE
Errore quando salvo un post vuoto

### ISSUE THREAD

**Issue by Danilospano00** [remo-candeli/ReminderMe#5]
![img salva 1](https://user-images.githubusercontent.com/75477572/119477790-92545b00-bd4f-11eb-9dc6-1d94e6fc407a.png)
![img salva 2](https://user-images.githubusercontent.com/75477572/119477784-91232e00-bd4f-11eb-9569-ab02c27a00fb.png)

**Comment by remo-candeli** [comment]
risolto ed aggiunta qualche funzionalita'
